import type { Metadata } from 'next';
import { Poppins, Montserrat, Lato } from 'next/font/google';
import './styles/globals.css';
import SideMenuNav from '@/components/layout/sideMenuNav';
import { StorageProviders } from '@/contexts/storageProviders';

const poppins = Poppins({
    variable: '--font-poppins',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
});

const montserrat = Montserrat({
    variable: '--font-montserrat',
    weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
    subsets: ['latin'],
});

const lato = Lato({
    variable: '--font-lato',
    weight: ['100', '300', '400', '700', '900'],
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Taskify',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br">
            <body
                className={`${poppins.variable} ${montserrat.variable} ${lato.variable} antialiased flex `}
            >
                <StorageProviders>
                    <SideMenuNav />
                    {children}
                </StorageProviders>
            </body>
        </html>
    );
}
